### ISSUE TITLE
Update the modelling species list

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/occ-cube-alien#29]
This list should be reviewed based on the last advances in selecting the species for risk assessment or any other usage of the european cube:
https://github.com/trias-project/occ-cube-alien/blob/master/references/modelling_species.tsv

**Comment by damianooldoni** [comment]
Oct 19, TrIAS core team will discuss this list and it can be a good moment to review it on GitHub as well.

**Comment by damianooldoni** [comment]
@amyjsdavis, @qgroom, @timadriaens: can you check that the list (link above) is updated? Many thanks.

**Comment by timadriaens** [comment]
@damianooldoni I checked. All the species we considered for PRA and for which we needed maps are there. I additionally added the last species under discussion (the snake, two plants and some birds mostly) to make sure we have all the cube we need for now. A few remarks:

- [ ] For Elaphe taeniura, we need to pool with the accepted name Orthriophis taeniurus (2455523) but I guess that is done automatically since it is a synonym? 
- [ ] Hedera hibernica is also under different names on gbif, the problem is discussed [here](https://github.com/trias-project/indicators/issues/92). So we need to pool data from 3 keys: c(6307044, 8168344, 8410115)

**Comment by timadriaens** [comment]
@damianooldoni should we also profit from this 'cube update' to include the alert list species of RIPARIAS (crayfish & aquatic plants) for the sake of efficiency?

**Comment by damianooldoni** [comment]
@timadriaens: yes, good idea. I will.

Notice also the following updates I would like to perform in the modelling species list based on the latest version of the GBIF Backbone:

NEW name (GBIF taxonKey) | OLD name (GBIF taxonKey) 
--- | ---
Megabalanus tintinnabulum [5166487](https://www.gbif.org/species/5166487) | Balanus tintinnabulum [2115692](https://www.gbif.org/species/2115692)
Crassula helmsii [5362054](https://www.gbif.org/species/5362054) | Crassula helmsii [8035075](https://www.gbif.org/species/8035075)
Eobania vermiculata [2294275](https://www.gbif.org/species/2294275) | Massylaea vermiculata [9291405](https://www.gbif.org/species/9291405)
Mustela vison [5218823](https://www.gbif.org/species/5218823) | Neovison vison [2433652](https://www.gbif.org/species/2433652)
Elaphe taeniura [8889878](https://www.gbif.org/species/8889878) | Orthriophis taeniurus [245523](https://www.gbif.org/species/245523)
