### ISSUE TITLE
Occurrences from new zenodo cube all over the place

### ISSUE THREAD

**Issue by SanderDevisscher** [trias-project/occ-cube-alien#44]
Observations of _Lithobates catesbeianus_ for the year 2018:
- Current zenodo cube (https://zenodo.org/records/10058400):
![image](https://github.com/trias-project/indicators/assets/16779320/a0c535f5-ab5c-47e8-b8d2-06a605bcf44f)

vs 

- Old zenodo cube (https://zenodo.org/records/5819028):
![image](https://github.com/trias-project/indicators/assets/16779320/a505b575-0738-447d-8566-ffa57a2ceb0b)

When I look at [be_alientaxa_cube.csv](https://zenodo.org/records/10058400/files/be_alientaxa_cube.csv) from zenodo it looks like the number of infected gridcells for Lithobates catesbeianus seems to be inflated compared to the previous version.

```
df <- read_csv(
  file = "https://zenodo.org/records/10058400/files/be_alientaxa_cube.csv?download=1",
  col_types = cols(
    year = col_double(),
    eea_cell_code = col_character(),
    taxonKey = col_double(),
    n = col_double(),
    min_coord_uncertainty = col_double()
  ),
  na = ""
)

test <- df %>% filter(taxonKey == 2427091)

df <- read_csv(
  file = "https://zenodo.org/records/5819028/files/be_alientaxa_cube.csv?download=1",
  col_types = cols(
    year = col_double(),
    eea_cell_code = col_character(),
    taxonKey = col_double(),
    n = col_double(),
    min_coord_uncertainty = col_double()
  ),
  na = ""
)

test <- df %>% filter(taxonKey == 2427091)
```

PS not certain this issue belongs here!

**Comment by SanderDevisscher** [comment]
Probably this issue is not limited to only _Lithobates catesbeianus_

**Comment by qgroom** [comment]
Something wrong has happened!
I think is should be posted here https://github.com/trias-project/occ-cube-alien

I think this is a good example of why the cube should have a link back in each row to the occurrence ID that was actually used. The current lack of provenance makes debugging such errors much more difficult.

**Comment by damianooldoni** [comment]
@SanderDevisscher: thanks for reporting this. Sorry for not having time to check this properly. I will try to find time this week. Probably wednesday I will. My first thought: the random assignment algorithm used for generating cube can modify the number of cells occupied if the occs have a high coordinate uncertainty.
I will also try to move the issue as suggested by @qgroom.

**Comment by damianooldoni** [comment]
I have only now seen the screenshots. Sorry! 
Actually it seems very strange, indeed. I will check it on Wednesday for sure!

**Comment by SanderDevisscher** [comment]
I would move the issue but i cannot 😞

**Comment by damianooldoni** [comment]
Yes, @SanderDevisscher. I can reproduce the unexpected behavior you encounter. It's a random assignment issue probably as it happens also for years with one occurrence only.

Notice that the problem is limited to the Belgian cube in `occ-cube-alien` (linked to the zenodo version you mention) and the Belgian cube produced in [occ-cube](https://github.com/trias-project/occ-cube) repo and linked to https://zenodo.org/records/10074895 which actually starts from the same interim sqlite database.

In other words, no issues with [cubes at species level](https://zenodo.org/records/10074895) of other countries and the cube of modelling species at European level contained in the same [zenodo package](https://zenodo.org/records/10058400) of the Belgian one. In other words, the code is correct. I remember I had some problems while performing the 3_assign_grid.R pipeline (laptop stopped) and instead of starting from scratch again I tried to fix them in the sqlite database directly to save time. I am sorry for this. I will make the BE cube again from scratch and update the zenodo repository afterwards. No change in code should be required.

**Comment by damianooldoni** [comment]
@SanderDevisscher: issue closed automatically. I have checked myself before pushing to `main` and publishing a new version on zenodo (see [20240118](https://zenodo.org/records/10527772) version), but I would like you double check it. Thanks.

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher: issue closed automatically. I have checked myself before pushing to `main` and publishing a new version on zenodo (see [20240118](https://zenodo.org/records/10527772) version), but I would like you double check it. Thanks.

I will
